fix: should send pending alarms message even when empty
Azure/Industrial-IoT pull request #1146
Opened 2021-05-04 14:31 UTC by peterbryntesson

fix: Added code to send pending alarms message even though the dictionary is empty

2021-05-04 15:08 UTC, simonjaeger approved these changes
LGTM

2021-05-05 06:24 UTC, peterbryntesson commented
UPDATE: Need to fix one more issue that Trumpf found. Don't approve just yet.

2021-05-05 13:07 UTC, simonjaeger requested changes

2021-05-05 13:07 UTC, simonjaeger commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/ISubscription.cs
> +        ///
Please fill in.

2021-05-05 13:07 UTC, simonjaeger commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
> +
Is this an empty line or is it my view?

2021-05-05 13:07 UTC, simonjaeger commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
> +                                subscription.OnSubscriptionStateChanged((bool)(value == SessionState.Running));
This has to be cast to a bool?

2021-05-05 13:10 UTC, peterbryntesson commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/ISubscription.cs
> +        ///
Fixed

2021-05-05 13:10 UTC, peterbryntesson commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
> +
It was. Deleted

2021-05-05 13:10 UTC, peterbryntesson commented on components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
> +                                subscription.OnSubscriptionStateChanged((bool)(value == SessionState.Running));
Remnant of another try. Removed.

2021-05-05 13:13 UTC, simonjaeger approved these changes

2021-05-06 14:00 UTC, mregen approved these changes

2021-05-06 14:01 UTC, merged