User guide configuration for events
Azure/Industrial-IoT pull request #1229
Opened 2021-06-15 12:00 UTC by peterbryntesson

User guide for configuring for events

2021-06-15 12:01 UTC, simonjaeger commented on docs/opc-event-configuration.md
> +Use configuration files for OPC UA Events in OPC Publisher
This you can make a header.

2021-06-15 12:01 UTC, simonjaeger approved these changes
LGTM

2021-06-16 09:45 UTC, koepalex commented
Nice write, is there also another doc planned with the generated output formats? If not I would add them to the description

2021-06-16 09:45 UTC, koepalex requested changes
:clock1:

2021-06-16 09:45 UTC, koepalex approved these changes
:shipit:

2021-06-16 10:14 UTC, peterbryntesson commented
> Nice write, is there also another doc planned with the generated output formats? If not I would add them to the description

Yes, I will write that in a separate doc later this week.

2021-06-16 10:15 UTC, merged