local metrics dashboard docs changes
Azure/Industrial-IoT pull request #1374
Opened 2021-09-02 12:01 UTC by monikavar

2021-09-02 12:42 UTC, koepalex approved these changes, later dismissed

2021-09-02 14:01 UTC, karok2m requested changes

2021-09-02 14:01 UTC, karok2m commented on docs/modules/publisher.md
> +To learn more about how to create a local metrics dashboard for OPC Publisher V2.7, please refer to the tutorial [here](./docs/tutorials/tut-publisher-local-metrics-dashboard/MetricsDashboard.md).
The link is invalid. It should most probably be `../tutorials/tut-publisher-local-metrics-dashboard/MetricsDashboard.md`.

2021-09-02 14:11 UTC, karok2m commented
@monikavar, you can use [HTTP/s and relative link checker](https://marketplace.visualstudio.com/items?itemName=blackmist.LinkCheckMD) VS Code extension to check if all links (relative and absolute) in the file are pointing to existing pages. It can also show other warnings such as usage of country codes in the links.

2021-09-03 08:43 UTC, monikavar commented on docs/modules/publisher.md
> +To learn more about how to create a local metrics dashboard for OPC Publisher V2.7, please refer to the tutorial [here](./docs/tutorials/tut-publisher-local-metrics-dashboard/MetricsDashboard.md).
fixed.

2021-09-03 08:48 UTC, karok2m approved these changes

2021-09-03 09:42 UTC, merged