Updated dependencies and remove projects that are not built
Azure/Industrial-IoT pull request #1386
Opened 2021-09-27 11:11 UTC by marcschier

Unit and integration tests are passing locally.

2021-09-27 13:00 UTC, mregen submitted a review, later dismissed

2021-09-27 15:26 UTC, mregen commented on modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.csproj
> +    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Symbols" Version="1.4.366.38" />
>OPCFoundation.NetStandard.Opc.Ua.Symbols [](http://example.com/codeflow?start=31&length=40)

better only use the OPCFoundation.NetStandard.Opc.Ua.Client lib here
to avoid the kestrel dependency

2021-09-27 15:31 UTC, mregen requested changes
sorry, I found one more thing... if possible switch to the seperate ua libraries

2021-09-27 15:54 UTC, marcschier commented on modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.csproj
> +    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Symbols" Version="1.4.366.38" />
I found that symbols brings in bouncy castle, which was used in SecureIoTHubToken.  I removed the entire code which we do not need in IoT Edge context anyway, and that is the only supported runtime context.

2021-09-27 16:01 UTC, cristipogacean approved these changes

2021-09-27 16:08 UTC, mregen approved these changes

2021-09-28 07:11 UTC, hansgschossmann approved these changes

2021-09-28 07:30 UTC, merged