Crpogace/2.7.180 fixes
Azure/Industrial-IoT pull request #696
Opened 2020-09-04 14:14 UTC by cristipogacean

* fixed creation of duplicate dataSetWriterId in job definition bug
* changed NodePublishBulkAsync behavior to generate a new dataSetWriterId respective a new dataset for every new api call
* added unit tests for Publish Bulk API
* added host bind mounts for layered IoT Edge deployments
* PkiRootPath is set to the same mount storage for all edge modules so that the modules can share the same pki store

2020-09-07 08:55 UTC, karok2m commented
Original pull requests for `release/2.7.180` branch:
* [Bugfix/publisher #689](https://github.com/Azure/Industrial-IoT/pull/689)
* [bind mounts for layered Iot Edge deployments #691](https://github.com/Azure/Industrial-IoT/pull/691)

2020-09-17 06:31 UTC, barnstee submitted a review, later dismissed

2020-09-17 12:53 UTC, karok2m commented
As per discussion with @cristipogacean, I am adding `in progress` label since he plans to add his other changes to `release/2.7.180` branch to this PR:
* [Hotfix/edge update #711](https://github.com/Azure/Industrial-IoT/pull/711)

2020-09-28 10:49 UTC, karok2m commented
Another set of changes from `release/2.7.180` branch that is present in this PR:
* fix updated job with new iot device conn. string #726

2020-09-29 09:15 UTC, karok2m requested changes

2020-09-29 10:24 UTC, cristipogacean commented on common/src/Microsoft.Azure.IIoT.Core/src/Hub/Services/IoTHubEdgeBaseDeployment.cs
> +                        ""createOptions"": ""{\""HostConfig\"":{\""PortBindings\"":{\""443/tcp\"":[{\""HostPort\"":\""443\""}],\""5671/tcp\"":[{\""HostPort\"":\""5671\""}],\""8883/tcp\"":[{\""HostPor
@karok2m, thanks for bringing this up! this change was unintended, most likely the result of some conflicted or failed  master merge!? it's fixed now

2020-09-29 10:48 UTC, karok2m approved these changes

2020-09-29 10:54 UTC, barnstee approved these changes

2020-09-29 12:26 UTC, merged