fix Publisher fail to start if max IoT Messages quota is reached
Azure/Industrial-IoT pull request #730
Opened 2020-09-23 13:03 UTC by dacolgit

2020-09-23 14:23 UTC, barnstee approved these changes

2020-09-23 14:58 UTC, karok2m requested changes

2020-09-23 14:58 UTC, karok2m commented on common/src/Microsoft.Azure.IIoT.Core/src/Utils/Retry.cs
> +                    }
@dacolgit, please revert back changes to `Retry.cs`. Default logic for continuation in `Retry` class is such that only exceptions of type `ITransientException` should be ignored. If you need a different retry condition, you can pass it from the caller as `cont` lambda.

Also, exceptions of type `IotHubQuotaExceededException` do not seem to be transient in nature, so immediate retries should not result in a successful call. So I would not even suggest passing that as a condition for retry continuation.

2020-09-24 11:54 UTC, karok2m approved these changes

2020-09-24 16:00 UTC, mregen approved these changes

2020-09-24 17:00 UTC, merged